// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const colors = {
 "red": "rgba(255, 51, 51, 1)",
 "green": "rgba(0, 178, 0, 1)",
 "blue": "rgba(51, 51, 255, 1)"
}

module.exports = colors;